//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class QTC_AssetManager_AssetTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(QTC.AssetManager.AssetType));
		L.RegVar("UnityObject", get_UnityObject, null);
		L.RegVar("GameObject", get_GameObject, null);
		L.RegVar("Material", get_Material, null);
		L.RegVar("Sprite", get_Sprite, null);
		L.RegVar("Texture", get_Texture, null);
		L.RegVar("AnimationClip", get_AnimationClip, null);
		L.RegVar("VideoClip", get_VideoClip, null);
		L.RegVar("Scene", get_Scene, null);
		L.RegVar("TextAsset", get_TextAsset, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<QTC.AssetManager.AssetType>.Check = CheckType;
		StackTraits<QTC.AssetManager.AssetType>.Push = Push;
	}

	static void Push(IntPtr L, QTC.AssetManager.AssetType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(QTC.AssetManager.AssetType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UnityObject(IntPtr L)
	{
		ToLua.Push(L, QTC.AssetManager.AssetType.UnityObject);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameObject(IntPtr L)
	{
		ToLua.Push(L, QTC.AssetManager.AssetType.GameObject);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Material(IntPtr L)
	{
		ToLua.Push(L, QTC.AssetManager.AssetType.Material);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Sprite(IntPtr L)
	{
		ToLua.Push(L, QTC.AssetManager.AssetType.Sprite);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Texture(IntPtr L)
	{
		ToLua.Push(L, QTC.AssetManager.AssetType.Texture);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AnimationClip(IntPtr L)
	{
		ToLua.Push(L, QTC.AssetManager.AssetType.AnimationClip);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_VideoClip(IntPtr L)
	{
		ToLua.Push(L, QTC.AssetManager.AssetType.VideoClip);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Scene(IntPtr L)
	{
		ToLua.Push(L, QTC.AssetManager.AssetType.Scene);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TextAsset(IntPtr L)
	{
		ToLua.Push(L, QTC.AssetManager.AssetType.TextAsset);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		QTC.AssetManager.AssetType o = (QTC.AssetManager.AssetType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

