//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_UIElements_VisualElementWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.UIElements.VisualElement), typeof(UnityEngine.UIElements.Focusable));
		L.RegFunction("Focus", Focus);
		L.RegFunction("SendEvent", SendEvent);
		L.RegFunction("SetEnabled", SetEnabled);
		L.RegFunction("MarkDirtyRepaint", MarkDirtyRepaint);
		L.RegFunction("ContainsPoint", ContainsPoint);
		L.RegFunction("Overlaps", Overlaps);
		L.RegFunction("ToString", ToString);
		L.RegFunction("GetClasses", GetClasses);
		L.RegFunction("ClearClassList", ClearClassList);
		L.RegFunction("AddToClassList", AddToClassList);
		L.RegFunction("RemoveFromClassList", RemoveFromClassList);
		L.RegFunction("ToggleInClassList", ToggleInClassList);
		L.RegFunction("EnableInClassList", EnableInClassList);
		L.RegFunction("ClassListContains", ClassListContains);
		L.RegFunction("FindAncestorUserData", FindAncestorUserData);
		L.RegFunction("Add", Add);
		L.RegFunction("Insert", Insert);
		L.RegFunction("Remove", Remove);
		L.RegFunction("RemoveAt", RemoveAt);
		L.RegFunction("Clear", Clear);
		L.RegFunction("ElementAt", ElementAt);
		L.RegFunction(".geti", get_Item);
		L.RegFunction("get_Item", get_Item);
		L.RegFunction("IndexOf", IndexOf);
		L.RegFunction("Children", Children);
		L.RegFunction("Sort", Sort);
		L.RegFunction("BringToFront", BringToFront);
		L.RegFunction("SendToBack", SendToBack);
		L.RegFunction("PlaceBehind", PlaceBehind);
		L.RegFunction("PlaceInFront", PlaceInFront);
		L.RegFunction("RemoveFromHierarchy", RemoveFromHierarchy);
		L.RegFunction("Contains", Contains);
		L.RegFunction("FindCommonAncestor", FindCommonAncestor);
		L.RegFunction("New", _CreateUnityEngine_UIElements_VisualElement);
		L.RegVar("this", _this, null);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("disabledUssClassName", get_disabledUssClassName, null);
		L.RegVar("viewDataKey", get_viewDataKey, set_viewDataKey);
		L.RegVar("userData", get_userData, set_userData);
		L.RegVar("canGrabFocus", get_canGrabFocus, null);
		L.RegVar("focusController", get_focusController, null);
		L.RegVar("usageHints", get_usageHints, set_usageHints);
		L.RegVar("transform", get_transform, null);
		L.RegVar("layout", get_layout, null);
		L.RegVar("contentRect", get_contentRect, null);
		L.RegVar("worldBound", get_worldBound, null);
		L.RegVar("localBound", get_localBound, null);
		L.RegVar("worldTransform", get_worldTransform, null);
		L.RegVar("pickingMode", get_pickingMode, set_pickingMode);
		L.RegVar("name", get_name, set_name);
		L.RegVar("enabledInHierarchy", get_enabledInHierarchy, null);
		L.RegVar("enabledSelf", get_enabledSelf, null);
		L.RegVar("visible", get_visible, set_visible);
		L.RegVar("generateVisualContent", get_generateVisualContent, set_generateVisualContent);
		L.RegVar("experimental", get_experimental, null);
		L.RegVar("hierarchy", get_hierarchy, null);
		L.RegVar("parent", get_parent, null);
		L.RegVar("panel", get_panel, null);
		L.RegVar("contentContainer", get_contentContainer, null);
		L.RegVar("childCount", get_childCount, null);
		L.RegVar("schedule", get_schedule, null);
		L.RegVar("style", get_style, null);
		L.RegVar("customStyle", get_customStyle, null);
		L.RegVar("styleSheets", get_styleSheets, null);
		L.RegVar("tooltip", get_tooltip, set_tooltip);
		L.RegVar("resolvedStyle", get_resolvedStyle, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_UIElements_VisualElement(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UnityEngine.UIElements.VisualElement obj = new UnityEngine.UIElements.VisualElement();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.UIElements.VisualElement.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _get_this(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			UnityEngine.UIElements.VisualElement o = obj[arg0];
			ToLua.PushObject(L, o);
			return 1;

		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _this(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushvalue(L, 1);
			LuaDLL.tolua_bindthis(L, _get_this, null);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Focus(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			obj.Focus();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			UnityEngine.UIElements.EventBase arg0 = (UnityEngine.UIElements.EventBase)ToLua.CheckObject<UnityEngine.UIElements.EventBase>(L, 2);
			obj.SendEvent(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetEnabled(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetEnabled(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int MarkDirtyRepaint(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			obj.MarkDirtyRepaint();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ContainsPoint(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			UnityEngine.Vector2 arg0 = ToLua.ToVector2(L, 2);
			bool o = obj.ContainsPoint(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Overlaps(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			UnityEngine.Rect arg0 = StackTraits<UnityEngine.Rect>.Check(L, 2);
			bool o = obj.Overlaps(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToString(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			string o = obj.ToString();
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetClasses(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			System.Collections.Generic.IEnumerable<string> o = obj.GetClasses();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearClassList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			obj.ClearClassList();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddToClassList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.AddToClassList(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveFromClassList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.RemoveFromClassList(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ToggleInClassList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.ToggleInClassList(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int EnableInClassList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			obj.EnableInClassList(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClassListContains(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.ClassListContains(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FindAncestorUserData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			object o = obj.FindAncestorUserData();
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Add(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			UnityEngine.UIElements.VisualElement arg0 = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 2);
			obj.Add(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Insert(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			UnityEngine.UIElements.VisualElement arg1 = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 3);
			obj.Insert(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Remove(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			UnityEngine.UIElements.VisualElement arg0 = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 2);
			obj.Remove(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveAt(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.RemoveAt(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			obj.Clear();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ElementAt(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			UnityEngine.UIElements.VisualElement o = obj.ElementAt(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Item(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			UnityEngine.UIElements.VisualElement o = obj[arg0];
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IndexOf(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			UnityEngine.UIElements.VisualElement arg0 = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 2);
			int o = obj.IndexOf(arg0);
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Children(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			System.Collections.Generic.IEnumerable<UnityEngine.UIElements.VisualElement> o = obj.Children();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Sort(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			System.Comparison<UnityEngine.UIElements.VisualElement> arg0 = (System.Comparison<UnityEngine.UIElements.VisualElement>)ToLua.CheckDelegate<System.Comparison<UnityEngine.UIElements.VisualElement>>(L, 2);
			obj.Sort(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int BringToFront(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			obj.BringToFront();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendToBack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			obj.SendToBack();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlaceBehind(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			UnityEngine.UIElements.VisualElement arg0 = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 2);
			obj.PlaceBehind(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int PlaceInFront(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			UnityEngine.UIElements.VisualElement arg0 = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 2);
			obj.PlaceInFront(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveFromHierarchy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			obj.RemoveFromHierarchy();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Contains(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			UnityEngine.UIElements.VisualElement arg0 = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 2);
			bool o = obj.Contains(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FindCommonAncestor(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 1);
			UnityEngine.UIElements.VisualElement arg0 = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 2);
			UnityEngine.UIElements.VisualElement o = obj.FindCommonAncestor(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_disabledUssClassName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, UnityEngine.UIElements.VisualElement.disabledUssClassName);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_viewDataKey(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			string ret = obj.viewDataKey;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index viewDataKey on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_userData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			object ret = obj.userData;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index userData on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_canGrabFocus(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			bool ret = obj.canGrabFocus;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index canGrabFocus on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_focusController(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.UIElements.FocusController ret = obj.focusController;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index focusController on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_usageHints(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.UIElements.UsageHints ret = obj.usageHints;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index usageHints on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_transform(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.UIElements.ITransform ret = obj.transform;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index transform on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_layout(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.Rect ret = obj.layout;
			ToLua.PushValue(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index layout on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_contentRect(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.Rect ret = obj.contentRect;
			ToLua.PushValue(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index contentRect on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_worldBound(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.Rect ret = obj.worldBound;
			ToLua.PushValue(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index worldBound on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_localBound(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.Rect ret = obj.localBound;
			ToLua.PushValue(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index localBound on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_worldTransform(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.Matrix4x4 ret = obj.worldTransform;
			ToLua.PushValue(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index worldTransform on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_pickingMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.UIElements.PickingMode ret = obj.pickingMode;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index pickingMode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_name(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			string ret = obj.name;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index name on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_enabledInHierarchy(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			bool ret = obj.enabledInHierarchy;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index enabledInHierarchy on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_enabledSelf(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			bool ret = obj.enabledSelf;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index enabledSelf on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_visible(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			bool ret = obj.visible;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index visible on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_generateVisualContent(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			System.Action<UnityEngine.UIElements.MeshGenerationContext> ret = obj.generateVisualContent;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index generateVisualContent on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_experimental(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.UIElements.IExperimentalFeatures ret = obj.experimental;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index experimental on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_hierarchy(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.UIElements.VisualElement.Hierarchy ret = obj.hierarchy;
			ToLua.PushValue(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index hierarchy on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_parent(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.UIElements.VisualElement ret = obj.parent;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index parent on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_panel(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.UIElements.IPanel ret = obj.panel;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index panel on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_contentContainer(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.UIElements.VisualElement ret = obj.contentContainer;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index contentContainer on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_childCount(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			int ret = obj.childCount;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index childCount on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_schedule(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.UIElements.IVisualElementScheduler ret = obj.schedule;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index schedule on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_style(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.UIElements.IStyle ret = obj.style;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index style on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_customStyle(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.UIElements.ICustomStyle ret = obj.customStyle;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index customStyle on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_styleSheets(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.UIElements.VisualElementStyleSheetSet ret = obj.styleSheets;
			ToLua.PushValue(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index styleSheets on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_tooltip(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			string ret = obj.tooltip;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index tooltip on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_resolvedStyle(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.UIElements.IResolvedStyle ret = obj.resolvedStyle;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index resolvedStyle on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_viewDataKey(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.viewDataKey = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index viewDataKey on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_userData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			object arg0 = ToLua.ToVarObject(L, 2);
			obj.userData = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index userData on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_usageHints(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.UIElements.UsageHints arg0 = (UnityEngine.UIElements.UsageHints)ToLua.CheckObject(L, 2, typeof(UnityEngine.UIElements.UsageHints));
			obj.usageHints = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index usageHints on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_pickingMode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			UnityEngine.UIElements.PickingMode arg0 = (UnityEngine.UIElements.PickingMode)ToLua.CheckObject(L, 2, typeof(UnityEngine.UIElements.PickingMode));
			obj.pickingMode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index pickingMode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_name(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.name = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index name on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_visible(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.visible = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index visible on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_generateVisualContent(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			System.Action<UnityEngine.UIElements.MeshGenerationContext> arg0 = (System.Action<UnityEngine.UIElements.MeshGenerationContext>)ToLua.CheckDelegate<System.Action<UnityEngine.UIElements.MeshGenerationContext>>(L, 2);
			obj.generateVisualContent = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index generateVisualContent on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_tooltip(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.VisualElement obj = (UnityEngine.UIElements.VisualElement)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.tooltip = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index tooltip on a nil value");
		}
	}
}

