---@class DG.Tweening.Tweener:DG.Tweening.Tween
---@field isRelative boolean
---@field active boolean
---@field fullPosition number
---@field hasLoops boolean
---@field playedOnce boolean
---@field position number
---@field ChangeStartValue fun(self:DG.Tweening.Tweener, newStartValue:System.Object, newDuration:number):DG.Tweening.Tweener
---@field ChangeEndValue fun(self:DG.Tweening.Tweener, newEndValue:System.Object, newDuration:number, snapStartValue:boolean):DG.Tweening.Tweener
---@field ChangeEndValue fun(self:DG.Tweening.Tweener, newEndValue:System.Object, snapStartValue:boolean):DG.Tweening.Tweener
---@field ChangeValues fun(self:DG.Tweening.Tweener, newStartValue:System.Object, newEndValue:System.Object, newDuration:number):DG.Tweening.Tweener
---@field Equals fun(self:System.Object, obj:System.Object):boolean
---@field GetHashCode fun(self:System.Object):number
---@field GetType fun(self:System.Object):System.Type
---@field ToString fun(self:System.Object):string
DG.Tweening.Tweener = {}
