---@class AssetType:System.Enum
---@field value__ number
---@field UnityObject AssetType
---@field GameObject AssetType
---@field Material AssetType
---@field Sprite AssetType
---@field Texture AssetType
---@field AnimationClip AssetType
---@field VideoClip AssetType
---@field Scene AssetType
---@field TextAsset AssetType
AssetType = {}
