---@class UnityEngine.Texture3D:UnityEngine.Texture
---@field depth number
---@field format UnityEngine.TextureFormat
---@field isReadable boolean
---@field mipmapCount number
---@field graphicsFormat UnityEngine.Experimental.Rendering.GraphicsFormat
---@field width number
---@field height number
---@field dimension UnityEngine.Rendering.TextureDimension
---@field wrapMode UnityEngine.TextureWrapMode
---@field wrapModeU UnityEngine.TextureWrapMode
---@field wrapModeV UnityEngine.TextureWrapMode
---@field wrapModeW UnityEngine.TextureWrapMode
---@field filterMode UnityEngine.FilterMode
---@field anisoLevel number
---@field mipMapBias number
---@field texelSize UnityEngine.Vector2
---@field updateCount System.UInt32
---@field imageContentsHash UnityEngine.Hash128
---@field name string
---@field hideFlags UnityEngine.HideFlags
---@field UpdateExternalTexture fun(nativeTex:System.IntPtr)
---@field GetPixels fun(miplevel:number):UnityEngine.Color[]
---@field GetPixels fun():UnityEngine.Color[]
---@field GetPixels32 fun(miplevel:number):UnityEngine.Color32[]
---@field GetPixels32 fun():UnityEngine.Color32[]
---@field SetPixels fun(colors:UnityEngine.Color[], miplevel:number)
---@field SetPixels fun(colors:UnityEngine.Color[])
---@field SetPixels32 fun(colors:UnityEngine.Color32[], miplevel:number)
---@field SetPixels32 fun(colors:UnityEngine.Color32[])
---@field CreateExternalTexture fun(width:number, height:number, depth:number, format:UnityEngine.TextureFormat, mipChain:boolean, nativeTex:System.IntPtr):UnityEngine.Texture3D
---@field Apply fun(updateMipmaps:boolean, makeNoLongerReadable:boolean)
---@field Apply fun(updateMipmaps:boolean)
---@field Apply fun()
---@field SetPixel fun(x:number, y:number, z:number, color:UnityEngine.Color)
---@field SetPixel fun(x:number, y:number, z:number, color:UnityEngine.Color, mipLevel:number)
---@field GetPixel fun(x:number, y:number, z:number):UnityEngine.Color
---@field GetPixel fun(x:number, y:number, z:number, mipLevel:number):UnityEngine.Color
---@field GetPixelBilinear fun(u:number, v:number, w:number):UnityEngine.Color
---@field GetPixelBilinear fun(u:number, v:number, w:number, mipLevel:number):UnityEngine.Color
---@field SetPixelData fun(data:T[], mipLevel:number, sourceDataStartIndex:number)
---@field GetPixelData fun(mipLevel:number):any
---@field GetNativeTexturePtr fun():System.IntPtr
---@field GetNativeTextureID fun():number
---@field IncrementUpdateCount fun()
---@field GetInstanceID fun():number
---@field GetHashCode fun():number
---@field Equals fun(other:System.Object):boolean
---@field ToString fun():string
---@field GetType fun():System.Type
UnityEngine.Texture3D = {}
