---@class UnityEngine.Sprite:UnityEngine.Object
---@field bounds UnityEngine.Bounds
---@field rect UnityEngine.Rect
---@field border UnityEngine.Vector4
---@field texture UnityEngine.Texture2D
---@field pixelsPerUnit number
---@field spriteAtlasTextureScale number
---@field associatedAlphaSplitTexture UnityEngine.Texture2D
---@field pivot UnityEngine.Vector2
---@field packed boolean
---@field packingMode UnityEngine.SpritePackingMode
---@field packingRotation UnityEngine.SpritePackingRotation
---@field textureRect UnityEngine.Rect
---@field textureRectOffset UnityEngine.Vector2
---@field vertices UnityEngine.Vector2[]
---@field triangles System.UInt16[]
---@field uv UnityEngine.Vector2[]
---@field name string
---@field hideFlags UnityEngine.HideFlags
---@field GetPhysicsShapeCount fun():number
---@field GetPhysicsShapePointCount fun(shapeIdx:number):number
---@field OverrideGeometry fun(vertices:UnityEngine.Vector2[], triangles:System.UInt16[])
---@field Create fun(texture:UnityEngine.Texture2D, rect:UnityEngine.Rect, pivot:UnityEngine.Vector2, pixelsPerUnit:number, extrude:System.UInt32, meshType:UnityEngine.SpriteMeshType, border:UnityEngine.Vector4, generateFallbackPhysicsShape:boolean):UnityEngine.Sprite
---@field Create fun(texture:UnityEngine.Texture2D, rect:UnityEngine.Rect, pivot:UnityEngine.Vector2, pixelsPerUnit:number, extrude:System.UInt32, meshType:UnityEngine.SpriteMeshType, border:UnityEngine.Vector4):UnityEngine.Sprite
---@field Create fun(texture:UnityEngine.Texture2D, rect:UnityEngine.Rect, pivot:UnityEngine.Vector2, pixelsPerUnit:number, extrude:System.UInt32, meshType:UnityEngine.SpriteMeshType):UnityEngine.Sprite
---@field Create fun(texture:UnityEngine.Texture2D, rect:UnityEngine.Rect, pivot:UnityEngine.Vector2, pixelsPerUnit:number, extrude:System.UInt32):UnityEngine.Sprite
---@field Create fun(texture:UnityEngine.Texture2D, rect:UnityEngine.Rect, pivot:UnityEngine.Vector2, pixelsPerUnit:number):UnityEngine.Sprite
---@field Create fun(texture:UnityEngine.Texture2D, rect:UnityEngine.Rect, pivot:UnityEngine.Vector2):UnityEngine.Sprite
---@field GetInstanceID fun():number
---@field GetHashCode fun():number
---@field Equals fun(other:System.Object):boolean
---@field ToString fun():string
---@field GetType fun():System.Type
UnityEngine.Sprite = {}
