---@class UnityEngine.Rigidbody:UnityEngine.Component
---@field velocity UnityEngine.Vector3
---@field angularVelocity UnityEngine.Vector3
---@field drag number
---@field angularDrag number
---@field mass number
---@field useGravity boolean
---@field maxDepenetrationVelocity number
---@field isKinematic boolean
---@field freezeRotation boolean
---@field constraints UnityEngine.RigidbodyConstraints
---@field collisionDetectionMode UnityEngine.CollisionDetectionMode
---@field centerOfMass UnityEngine.Vector3
---@field worldCenterOfMass UnityEngine.Vector3
---@field inertiaTensorRotation UnityEngine.Quaternion
---@field inertiaTensor UnityEngine.Vector3
---@field detectCollisions boolean
---@field position UnityEngine.Vector3
---@field rotation UnityEngine.Quaternion
---@field interpolation UnityEngine.RigidbodyInterpolation
---@field solverIterations number
---@field sleepThreshold number
---@field maxAngularVelocity number
---@field solverVelocityIterations number
---@field sleepVelocity number
---@field sleepAngularVelocity number
---@field useConeFriction boolean
---@field solverIterationCount number
---@field solverVelocityIterationCount number
---@field transform UnityEngine.Transform
---@field gameObject UnityEngine.GameObject
---@field tag string
---@field rigidbody UnityEngine.Component
---@field rigidbody2D UnityEngine.Component
---@field camera UnityEngine.Component
---@field light UnityEngine.Component
---@field animation UnityEngine.Component
---@field constantForce UnityEngine.Component
---@field renderer UnityEngine.Component
---@field audio UnityEngine.Component
---@field networkView UnityEngine.Component
---@field collider UnityEngine.Component
---@field collider2D UnityEngine.Component
---@field hingeJoint UnityEngine.Component
---@field particleSystem UnityEngine.Component
---@field name string
---@field hideFlags UnityEngine.HideFlags
---@field SetDensity fun(density:number)
---@field MovePosition fun(position:UnityEngine.Vector3)
---@field MoveRotation fun(rot:UnityEngine.Quaternion)
---@field Sleep fun()
---@field IsSleeping fun():boolean
---@field WakeUp fun()
---@field ResetCenterOfMass fun()
---@field ResetInertiaTensor fun()
---@field GetRelativePointVelocity fun(relativePoint:UnityEngine.Vector3):UnityEngine.Vector3
---@field GetPointVelocity fun(worldPoint:UnityEngine.Vector3):UnityEngine.Vector3
---@field SetMaxAngularVelocity fun(a:number)
---@field AddForce fun(force:UnityEngine.Vector3, mode:UnityEngine.ForceMode)
---@field AddForce fun(force:UnityEngine.Vector3)
---@field AddForce fun(x:number, y:number, z:number, mode:UnityEngine.ForceMode)
---@field AddForce fun(x:number, y:number, z:number)
---@field AddRelativeForce fun(force:UnityEngine.Vector3, mode:UnityEngine.ForceMode)
---@field AddRelativeForce fun(force:UnityEngine.Vector3)
---@field AddRelativeForce fun(x:number, y:number, z:number, mode:UnityEngine.ForceMode)
---@field AddRelativeForce fun(x:number, y:number, z:number)
---@field AddTorque fun(torque:UnityEngine.Vector3, mode:UnityEngine.ForceMode)
---@field AddTorque fun(torque:UnityEngine.Vector3)
---@field AddTorque fun(x:number, y:number, z:number, mode:UnityEngine.ForceMode)
---@field AddTorque fun(x:number, y:number, z:number)
---@field AddRelativeTorque fun(torque:UnityEngine.Vector3, mode:UnityEngine.ForceMode)
---@field AddRelativeTorque fun(torque:UnityEngine.Vector3)
---@field AddRelativeTorque fun(x:number, y:number, z:number, mode:UnityEngine.ForceMode)
---@field AddRelativeTorque fun(x:number, y:number, z:number)
---@field AddForceAtPosition fun(force:UnityEngine.Vector3, position:UnityEngine.Vector3, mode:UnityEngine.ForceMode)
---@field AddForceAtPosition fun(force:UnityEngine.Vector3, position:UnityEngine.Vector3)
---@field AddExplosionForce fun(explosionForce:number, explosionPosition:UnityEngine.Vector3, explosionRadius:number, upwardsModifier:number, mode:UnityEngine.ForceMode)
---@field AddExplosionForce fun(explosionForce:number, explosionPosition:UnityEngine.Vector3, explosionRadius:number, upwardsModifier:number)
---@field AddExplosionForce fun(explosionForce:number, explosionPosition:UnityEngine.Vector3, explosionRadius:number)
---@field ClosestPointOnBounds fun(position:UnityEngine.Vector3):UnityEngine.Vector3
---@field SweepTest fun(direction:UnityEngine.Vector3, hitInfo:UnityEngine.RaycastHit&, maxDistance:number, queryTriggerInteraction:UnityEngine.QueryTriggerInteraction):boolean
---@field SweepTest fun(direction:UnityEngine.Vector3, hitInfo:UnityEngine.RaycastHit&, maxDistance:number):boolean
---@field SweepTest fun(direction:UnityEngine.Vector3, hitInfo:UnityEngine.RaycastHit&):boolean
---@field SweepTestAll fun(direction:UnityEngine.Vector3, maxDistance:number, queryTriggerInteraction:UnityEngine.QueryTriggerInteraction):UnityEngine.RaycastHit[]
---@field SweepTestAll fun(direction:UnityEngine.Vector3, maxDistance:number):UnityEngine.RaycastHit[]
---@field SweepTestAll fun(direction:UnityEngine.Vector3):UnityEngine.RaycastHit[]
---@field GetComponent fun(type:System.Type):UnityEngine.Component
---@field GetComponent fun():nil
---@field TryGetComponent fun(type:System.Type, component:UnityEngine.Component&):boolean
---@field TryGetComponent fun(component:nil):boolean
---@field GetComponent fun(type:string):UnityEngine.Component
---@field GetComponentInChildren fun(t:System.Type, includeInactive:boolean):UnityEngine.Component
---@field GetComponentInChildren fun(t:System.Type):UnityEngine.Component
---@field GetComponentInChildren fun(includeInactive:boolean):nil
---@field GetComponentInChildren fun():nil
---@field GetComponentsInChildren fun(t:System.Type, includeInactive:boolean):UnityEngine.Component[]
---@field GetComponentsInChildren fun(t:System.Type):UnityEngine.Component[]
---@field GetComponentsInChildren fun(includeInactive:boolean):T[]
---@field GetComponentsInChildren fun():T[]
---@field GetComponentInParent fun(t:System.Type):UnityEngine.Component
---@field GetComponentInParent fun():nil
---@field GetComponentsInParent fun(t:System.Type, includeInactive:boolean):UnityEngine.Component[]
---@field GetComponentsInParent fun(t:System.Type):UnityEngine.Component[]
---@field GetComponentsInParent fun(includeInactive:boolean):T[]
---@field GetComponentsInParent fun():T[]
---@field GetComponents fun(type:System.Type):UnityEngine.Component[]
---@field GetComponents fun():T[]
---@field CompareTag fun(tag:string):boolean
---@field SendMessageUpwards fun(methodName:string, value:System.Object, options:UnityEngine.SendMessageOptions)
---@field SendMessageUpwards fun(methodName:string, value:System.Object)
---@field SendMessageUpwards fun(methodName:string)
---@field SendMessageUpwards fun(methodName:string, options:UnityEngine.SendMessageOptions)
---@field SendMessage fun(methodName:string, value:System.Object)
---@field SendMessage fun(methodName:string)
---@field SendMessage fun(methodName:string, value:System.Object, options:UnityEngine.SendMessageOptions)
---@field SendMessage fun(methodName:string, options:UnityEngine.SendMessageOptions)
---@field BroadcastMessage fun(methodName:string, parameter:System.Object, options:UnityEngine.SendMessageOptions)
---@field BroadcastMessage fun(methodName:string, parameter:System.Object)
---@field BroadcastMessage fun(methodName:string)
---@field BroadcastMessage fun(methodName:string, options:UnityEngine.SendMessageOptions)
---@field GetInstanceID fun():number
---@field GetHashCode fun():number
---@field Equals fun(other:System.Object):boolean
---@field ToString fun():string
---@field GetType fun():System.Type
UnityEngine.Rigidbody = {}
