---@class UnityEngine.Video.VideoPlayer:UnityEngine.Behaviour
---@field source UnityEngine.Video.VideoSource
---@field url string
---@field clip UnityEngine.Video.VideoClip
---@field renderMode UnityEngine.Video.VideoRenderMode
---@field targetCamera UnityEngine.Camera
---@field targetTexture UnityEngine.RenderTexture
---@field targetMaterialRenderer UnityEngine.Renderer
---@field targetMaterialProperty string
---@field aspectRatio UnityEngine.Video.VideoAspectRatio
---@field targetCameraAlpha number
---@field targetCamera3DLayout UnityEngine.Video.Video3DLayout
---@field texture UnityEngine.Texture
---@field isPrepared boolean
---@field waitForFirstFrame boolean
---@field playOnAwake boolean
---@field isPlaying boolean
---@field isPaused boolean
---@field canSetTime boolean
---@field time System.Double
---@field frame System.Int64
---@field clockTime System.Double
---@field canStep boolean
---@field canSetPlaybackSpeed boolean
---@field playbackSpeed number
---@field isLooping boolean
---@field canSetTimeSource boolean
---@field timeSource UnityEngine.Video.VideoTimeSource
---@field timeReference UnityEngine.Video.VideoTimeReference
---@field externalReferenceTime System.Double
---@field canSetSkipOnDrop boolean
---@field skipOnDrop boolean
---@field frameCount number
---@field frameRate number
---@field length System.Double
---@field width System.UInt32
---@field height System.UInt32
---@field pixelAspectRatioNumerator System.UInt32
---@field pixelAspectRatioDenominator System.UInt32
---@field audioTrackCount System.UInt16
---@field controlledAudioTrackMaxCount System.UInt16
---@field controlledAudioTrackCount System.UInt16
---@field audioOutputMode UnityEngine.Video.VideoAudioOutputMode
---@field canSetDirectAudioVolume boolean
---@field sendFrameReadyEvents boolean
---@field enabled boolean
---@field isActiveAndEnabled boolean
---@field transform UnityEngine.Transform
---@field gameObject UnityEngine.GameObject
---@field tag string
---@field rigidbody UnityEngine.Component
---@field rigidbody2D UnityEngine.Component
---@field camera UnityEngine.Component
---@field light UnityEngine.Component
---@field animation UnityEngine.Component
---@field constantForce UnityEngine.Component
---@field renderer UnityEngine.Component
---@field audio UnityEngine.Component
---@field networkView UnityEngine.Component
---@field collider UnityEngine.Component
---@field collider2D UnityEngine.Component
---@field hingeJoint UnityEngine.Component
---@field particleSystem UnityEngine.Component
---@field name string
---@field hideFlags UnityEngine.HideFlags
---@field Prepare fun()
---@field Play fun()
---@field Pause fun()
---@field Stop fun()
---@field StepForward fun()
---@field GetAudioLanguageCode fun(trackIndex:System.UInt16):string
---@field GetAudioChannelCount fun(trackIndex:System.UInt16):System.UInt16
---@field GetAudioSampleRate fun(trackIndex:System.UInt16):System.UInt32
---@field EnableAudioTrack fun(trackIndex:System.UInt16, enabled:boolean)
---@field IsAudioTrackEnabled fun(trackIndex:System.UInt16):boolean
---@field GetDirectAudioVolume fun(trackIndex:System.UInt16):number
---@field SetDirectAudioVolume fun(trackIndex:System.UInt16, volume:number)
---@field GetDirectAudioMute fun(trackIndex:System.UInt16):boolean
---@field SetDirectAudioMute fun(trackIndex:System.UInt16, mute:boolean)
---@field GetTargetAudioSource fun(trackIndex:System.UInt16):UnityEngine.AudioSource
---@field SetTargetAudioSource fun(trackIndex:System.UInt16, source:UnityEngine.AudioSource)
---@field GetComponent fun(type:System.Type):UnityEngine.Component
---@field GetComponent fun():nil
---@field TryGetComponent fun(type:System.Type, component:UnityEngine.Component&):boolean
---@field TryGetComponent fun(component:nil):boolean
---@field GetComponent fun(type:string):UnityEngine.Component
---@field GetComponentInChildren fun(t:System.Type, includeInactive:boolean):UnityEngine.Component
---@field GetComponentInChildren fun(t:System.Type):UnityEngine.Component
---@field GetComponentInChildren fun(includeInactive:boolean):nil
---@field GetComponentInChildren fun():nil
---@field GetComponentsInChildren fun(t:System.Type, includeInactive:boolean):UnityEngine.Component[]
---@field GetComponentsInChildren fun(t:System.Type):UnityEngine.Component[]
---@field GetComponentsInChildren fun(includeInactive:boolean):T[]
---@field GetComponentsInChildren fun():T[]
---@field GetComponentInParent fun(t:System.Type):UnityEngine.Component
---@field GetComponentInParent fun():nil
---@field GetComponentsInParent fun(t:System.Type, includeInactive:boolean):UnityEngine.Component[]
---@field GetComponentsInParent fun(t:System.Type):UnityEngine.Component[]
---@field GetComponentsInParent fun(includeInactive:boolean):T[]
---@field GetComponentsInParent fun():T[]
---@field GetComponents fun(type:System.Type):UnityEngine.Component[]
---@field GetComponents fun():T[]
---@field CompareTag fun(tag:string):boolean
---@field SendMessageUpwards fun(methodName:string, value:System.Object, options:UnityEngine.SendMessageOptions)
---@field SendMessageUpwards fun(methodName:string, value:System.Object)
---@field SendMessageUpwards fun(methodName:string)
---@field SendMessageUpwards fun(methodName:string, options:UnityEngine.SendMessageOptions)
---@field SendMessage fun(methodName:string, value:System.Object)
---@field SendMessage fun(methodName:string)
---@field SendMessage fun(methodName:string, value:System.Object, options:UnityEngine.SendMessageOptions)
---@field SendMessage fun(methodName:string, options:UnityEngine.SendMessageOptions)
---@field BroadcastMessage fun(methodName:string, parameter:System.Object, options:UnityEngine.SendMessageOptions)
---@field BroadcastMessage fun(methodName:string, parameter:System.Object)
---@field BroadcastMessage fun(methodName:string)
---@field BroadcastMessage fun(methodName:string, options:UnityEngine.SendMessageOptions)
---@field GetInstanceID fun():number
---@field GetHashCode fun():number
---@field Equals fun(other:System.Object):boolean
---@field ToString fun():string
---@field GetType fun():System.Type
UnityEngine.Video.VideoPlayer = {}
