---@class UnityEngine.AnimatorStateInfo:System.ValueType
---@field fullPathHash number
---@field nameHash number
---@field shortNameHash number
---@field normalizedTime number
---@field length number
---@field speed number
---@field speedMultiplier number
---@field tagHash number
---@field loop boolean
---@field IsName fun(name:string):boolean
---@field IsTag fun(tag:string):boolean
---@field Equals fun(obj:System.Object):boolean
---@field GetHashCode fun():number
---@field ToString fun():string
---@field GetType fun():System.Type
UnityEngine.AnimatorStateInfo = {}
