---@class UnityEngine.Rect:System.ValueType
---@field zero UnityEngine.Rect
---@field x number
---@field y number
---@field position UnityEngine.Vector2
---@field center UnityEngine.Vector2
---@field min UnityEngine.Vector2
---@field max UnityEngine.Vector2
---@field width number
---@field height number
---@field size UnityEngine.Vector2
---@field xMin number
---@field yMin number
---@field xMax number
---@field yMax number
---@field left number
---@field right number
---@field top number
---@field bottom number
---@field MinMaxRect fun(xmin:number, ymin:number, xmax:number, ymax:number):UnityEngine.Rect
---@field Set fun(x:number, y:number, width:number, height:number)
---@field Contains fun(point:UnityEngine.Vector2):boolean
---@field Contains fun(point:UnityEngine.Vector3):boolean
---@field Contains fun(point:UnityEngine.Vector3, allowInverse:boolean):boolean
---@field Overlaps fun(other:UnityEngine.Rect):boolean
---@field Overlaps fun(other:UnityEngine.Rect, allowInverse:boolean):boolean
---@field NormalizedToPoint fun(rectangle:UnityEngine.Rect, normalizedRectCoordinates:UnityEngine.Vector2):UnityEngine.Vector2
---@field PointToNormalized fun(rectangle:UnityEngine.Rect, point:UnityEngine.Vector2):UnityEngine.Vector2
---@field GetHashCode fun():number
---@field Equals fun(other:System.Object):boolean
---@field Equals fun(other:UnityEngine.Rect):boolean
---@field ToString fun():string
---@field ToString fun(format:string):string
---@field ToString fun(format:string, formatProvider:System.IFormatProvider):string
---@field GetType fun():System.Type
UnityEngine.Rect = {}
