---@class UnityEngine.Matrix4x4:System.ValueType
---@field rotation UnityEngine.Quaternion
---@field lossyScale UnityEngine.Vector3
---@field isIdentity boolean
---@field determinant number
---@field decomposeProjection UnityEngine.FrustumPlanes
---@field inverse UnityEngine.Matrix4x4
---@field transpose UnityEngine.Matrix4x4
---@field Item number
---@field Item number
---@field zero UnityEngine.Matrix4x4
---@field identity UnityEngine.Matrix4x4
---@field ValidTRS fun():boolean
---@field Determinant fun(m:UnityEngine.Matrix4x4):number
---@field TRS fun(pos:UnityEngine.Vector3, q:UnityEngine.Quaternion, s:UnityEngine.Vector3):UnityEngine.Matrix4x4
---@field SetTRS fun(pos:UnityEngine.Vector3, q:UnityEngine.Quaternion, s:UnityEngine.Vector3)
---@field Inverse3DAffine fun(input:UnityEngine.Matrix4x4, result:UnityEngine.Matrix4x4&):boolean
---@field Inverse fun(m:UnityEngine.Matrix4x4):UnityEngine.Matrix4x4
---@field Transpose fun(m:UnityEngine.Matrix4x4):UnityEngine.Matrix4x4
---@field Ortho fun(left:number, right:number, bottom:number, top:number, zNear:number, zFar:number):UnityEngine.Matrix4x4
---@field Perspective fun(fov:number, aspect:number, zNear:number, zFar:number):UnityEngine.Matrix4x4
---@field LookAt fun(from:UnityEngine.Vector3, to:UnityEngine.Vector3, up:UnityEngine.Vector3):UnityEngine.Matrix4x4
---@field Frustum fun(left:number, right:number, bottom:number, top:number, zNear:number, zFar:number):UnityEngine.Matrix4x4
---@field Frustum fun(fp:UnityEngine.FrustumPlanes):UnityEngine.Matrix4x4
---@field GetHashCode fun():number
---@field Equals fun(other:System.Object):boolean
---@field Equals fun(other:UnityEngine.Matrix4x4):boolean
---@field GetColumn fun(index:number):UnityEngine.Vector4
---@field GetRow fun(index:number):UnityEngine.Vector4
---@field SetColumn fun(index:number, column:UnityEngine.Vector4)
---@field SetRow fun(index:number, row:UnityEngine.Vector4)
---@field MultiplyPoint fun(point:UnityEngine.Vector3):UnityEngine.Vector3
---@field MultiplyPoint3x4 fun(point:UnityEngine.Vector3):UnityEngine.Vector3
---@field MultiplyVector fun(vector:UnityEngine.Vector3):UnityEngine.Vector3
---@field TransformPlane fun(plane:UnityEngine.Plane):UnityEngine.Plane
---@field Scale fun(vector:UnityEngine.Vector3):UnityEngine.Matrix4x4
---@field Translate fun(vector:UnityEngine.Vector3):UnityEngine.Matrix4x4
---@field Rotate fun(q:UnityEngine.Quaternion):UnityEngine.Matrix4x4
---@field ToString fun():string
---@field ToString fun(format:string):string
---@field ToString fun(format:string, formatProvider:System.IFormatProvider):string
---@field GetType fun():System.Type
UnityEngine.Matrix4x4 = {}
