---@class EventSystems.BaseEventData:EventSystems.AbstractEventData
---@field currentInputModule EventSystems.BaseInputModule
---@field selectedObject GameObject
---@field used boolean
---@field Reset fun(self:EventSystems.AbstractEventData)
---@field Use fun(self:EventSystems.AbstractEventData)
---@field Equals fun(self:System.Object, obj:System.Object):boolean
---@field GetHashCode fun(self:System.Object):number
---@field GetType fun(self:System.Object):System.Type
---@field ToString fun(self:System.Object):string
EventSystems.BaseEventData = {}
