---@class AudioSource:AudioBehaviour
---@field panLevel number
---@field pan number
---@field volume number
---@field pitch number
---@field time number
---@field timeSamples number
---@field clip AudioClip
---@field outputAudioMixerGroup Audio.AudioMixerGroup
---@field isPlaying boolean
---@field isVirtual boolean
---@field loop boolean
---@field ignoreListenerVolume boolean
---@field playOnAwake boolean
---@field ignoreListenerPause boolean
---@field velocityUpdateMode AudioVelocityUpdateMode
---@field panStereo number
---@field spatialBlend number
---@field spatialize boolean
---@field spatializePostEffects boolean
---@field reverbZoneMix number
---@field bypassEffects boolean
---@field bypassListenerEffects boolean
---@field bypassReverbZones boolean
---@field dopplerLevel number
---@field spread number
---@field priority number
---@field mute boolean
---@field minDistance number
---@field maxDistance number
---@field rolloffMode AudioRolloffMode
---@field minVolume number
---@field maxVolume number
---@field rolloffFactor number
---@field enabled boolean
---@field isActiveAndEnabled boolean
---@field transform Transform
---@field gameObject GameObject
---@field tag string
---@field rigidbody Component
---@field rigidbody2D Component
---@field camera Component
---@field light Component
---@field animation Component
---@field constantForce Component
---@field renderer Component
---@field audio Component
---@field networkView Component
---@field collider Component
---@field collider2D Component
---@field hingeJoint Component
---@field particleSystem Component
---@field name string
---@field hideFlags HideFlags
---@field Play fun(self:AudioSource)
---@field Play fun(self:AudioSource, delay:number)
---@field PlayDelayed fun(self:AudioSource, delay:number)
---@field PlayScheduled fun(self:AudioSource, time:System.Double)
---@field PlayOneShot fun(self:AudioSource, clip:AudioClip)
---@field PlayOneShot fun(self:AudioSource, clip:AudioClip, volumeScale:number)
---@field SetScheduledStartTime fun(self:AudioSource, time:System.Double)
---@field SetScheduledEndTime fun(self:AudioSource, time:System.Double)
---@field Stop fun(self:AudioSource)
---@field Pause fun(self:AudioSource)
---@field UnPause fun(self:AudioSource)
---@field PlayClipAtPoint fun(clip:AudioClip, position:Vector3)
---@field PlayClipAtPoint fun(clip:AudioClip, position:Vector3, volume:number)
---@field SetCustomCurve fun(self:AudioSource, type:AudioSourceCurveType, curve:AnimationCurve)
---@field GetCustomCurve fun(self:AudioSource, type:AudioSourceCurveType):AnimationCurve
---@field GetOutputData fun(self:AudioSource, numSamples:number, channel:number):System.Single[]
---@field GetOutputData fun(self:AudioSource, samples:System.Single[], channel:number)
---@field GetSpectrumData fun(self:AudioSource, numSamples:number, channel:number, window:FFTWindow):System.Single[]
---@field GetSpectrumData fun(self:AudioSource, samples:System.Single[], channel:number, window:FFTWindow)
---@field SetSpatializerFloat fun(self:AudioSource, index:number, value:number):boolean
---@field GetSpatializerFloat fun(self:AudioSource, index:number, value:System.Single&):boolean
---@field GetAmbisonicDecoderFloat fun(self:AudioSource, index:number, value:System.Single&):boolean
---@field SetAmbisonicDecoderFloat fun(self:AudioSource, index:number, value:number):boolean
---@field GetComponent fun(self:Component, type:System.Type):Component
---@field GetComponent fun(self:Component):nil
---@field TryGetComponent fun(self:Component, type:System.Type, component:Component&):boolean
---@field TryGetComponent fun(self:Component, component:nil):boolean
---@field GetComponent fun(self:Component, type:string):Component
---@field GetComponentInChildren fun(self:Component, t:System.Type, includeInactive:boolean):Component
---@field GetComponentInChildren fun(self:Component, t:System.Type):Component
---@field GetComponentInChildren fun(self:Component, includeInactive:boolean):nil
---@field GetComponentInChildren fun(self:Component):nil
---@field GetComponentsInChildren fun(self:Component, t:System.Type, includeInactive:boolean):Component[]
---@field GetComponentsInChildren fun(self:Component, t:System.Type):Component[]
---@field GetComponentsInChildren fun(self:Component, includeInactive:boolean):T[]
---@field GetComponentsInChildren fun(self:Component, includeInactive:boolean, result:nil)
---@field GetComponentsInChildren fun(self:Component):T[]
---@field GetComponentsInChildren fun(self:Component, results:nil)
---@field GetComponentInParent fun(self:Component, t:System.Type):Component
---@field GetComponentInParent fun(self:Component):nil
---@field GetComponentsInParent fun(self:Component, t:System.Type, includeInactive:boolean):Component[]
---@field GetComponentsInParent fun(self:Component, t:System.Type):Component[]
---@field GetComponentsInParent fun(self:Component, includeInactive:boolean):T[]
---@field GetComponentsInParent fun(self:Component, includeInactive:boolean, results:nil)
---@field GetComponentsInParent fun(self:Component):T[]
---@field GetComponents fun(self:Component, type:System.Type):Component[]
---@field GetComponents fun(self:Component, type:System.Type, results:System.Collections.Generic.List`1[[Component, CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]])
---@field GetComponents fun(self:Component, results:nil)
---@field GetComponents fun(self:Component):T[]
---@field CompareTag fun(self:Component, tag:string):boolean
---@field SendMessageUpwards fun(self:Component, methodName:string, value:System.Object, options:SendMessageOptions)
---@field SendMessageUpwards fun(self:Component, methodName:string, value:System.Object)
---@field SendMessageUpwards fun(self:Component, methodName:string)
---@field SendMessageUpwards fun(self:Component, methodName:string, options:SendMessageOptions)
---@field SendMessage fun(self:Component, methodName:string, value:System.Object)
---@field SendMessage fun(self:Component, methodName:string)
---@field SendMessage fun(self:Component, methodName:string, value:System.Object, options:SendMessageOptions)
---@field SendMessage fun(self:Component, methodName:string, options:SendMessageOptions)
---@field BroadcastMessage fun(self:Component, methodName:string, parameter:System.Object, options:SendMessageOptions)
---@field BroadcastMessage fun(self:Component, methodName:string, parameter:System.Object)
---@field BroadcastMessage fun(self:Component, methodName:string)
---@field BroadcastMessage fun(self:Component, methodName:string, options:SendMessageOptions)
---@field GetInstanceID fun(self:Object):number
---@field GetHashCode fun(self:Object):number
---@field Equals fun(self:Object, other:System.Object):boolean
---@field ToString fun(self:Object):string
---@field GetType fun(self:System.Object):System.Type
AudioSource = {}
