---@class UnityEngine.Animator:UnityEngine.Behaviour
---@field isOptimizable boolean
---@field isHuman boolean
---@field hasRootMotion boolean
---@field humanScale number
---@field isInitialized boolean
---@field deltaPosition UnityEngine.Vector3
---@field deltaRotation UnityEngine.Quaternion
---@field velocity UnityEngine.Vector3
---@field angularVelocity UnityEngine.Vector3
---@field rootPosition UnityEngine.Vector3
---@field rootRotation UnityEngine.Quaternion
---@field applyRootMotion boolean
---@field linearVelocityBlending boolean
---@field animatePhysics boolean
---@field updateMode UnityEngine.AnimatorUpdateMode
---@field hasTransformHierarchy boolean
---@field gravityWeight number
---@field bodyPosition UnityEngine.Vector3
---@field bodyRotation UnityEngine.Quaternion
---@field stabilizeFeet boolean
---@field layerCount number
---@field parameters UnityEngine.AnimatorControllerParameter[]
---@field parameterCount number
---@field feetPivotActive number
---@field pivotWeight number
---@field pivotPosition UnityEngine.Vector3
---@field isMatchingTarget boolean
---@field speed number
---@field targetPosition UnityEngine.Vector3
---@field targetRotation UnityEngine.Quaternion
---@field cullingMode UnityEngine.AnimatorCullingMode
---@field playbackTime number
---@field recorderStartTime number
---@field recorderStopTime number
---@field recorderMode UnityEngine.AnimatorRecorderMode
---@field runtimeAnimatorController UnityEngine.RuntimeAnimatorController
---@field hasBoundPlayables boolean
---@field avatar UnityEngine.Avatar
---@field playableGraph UnityEngine.Playables.PlayableGraph
---@field layersAffectMassCenter boolean
---@field leftFeetBottomHeight number
---@field rightFeetBottomHeight number
---@field logWarnings boolean
---@field fireEvents boolean
---@field keepAnimatorControllerStateOnDisable boolean
---@field enabled boolean
---@field isActiveAndEnabled boolean
---@field transform UnityEngine.Transform
---@field gameObject UnityEngine.GameObject
---@field tag string
---@field rigidbody UnityEngine.Component
---@field rigidbody2D UnityEngine.Component
---@field camera UnityEngine.Component
---@field light UnityEngine.Component
---@field animation UnityEngine.Component
---@field constantForce UnityEngine.Component
---@field renderer UnityEngine.Component
---@field audio UnityEngine.Component
---@field networkView UnityEngine.Component
---@field collider UnityEngine.Component
---@field collider2D UnityEngine.Component
---@field hingeJoint UnityEngine.Component
---@field particleSystem UnityEngine.Component
---@field name string
---@field hideFlags UnityEngine.HideFlags
---@field GetCurrentAnimationClipState fun(layerIndex:number):UnityEngine.AnimationInfo[]
---@field GetNextAnimationClipState fun(layerIndex:number):UnityEngine.AnimationInfo[]
---@field Stop fun()
---@field GetFloat fun(name:string):number
---@field GetFloat fun(id:number):number
---@field SetFloat fun(name:string, value:number)
---@field SetFloat fun(name:string, value:number, dampTime:number, deltaTime:number)
---@field SetFloat fun(id:number, value:number)
---@field SetFloat fun(id:number, value:number, dampTime:number, deltaTime:number)
---@field GetBool fun(name:string):boolean
---@field GetBool fun(id:number):boolean
---@field SetBool fun(name:string, value:boolean)
---@field SetBool fun(id:number, value:boolean)
---@field GetInteger fun(name:string):number
---@field GetInteger fun(id:number):number
---@field SetInteger fun(name:string, value:number)
---@field SetInteger fun(id:number, value:number)
---@field SetTrigger fun(name:string)
---@field SetTrigger fun(id:number)
---@field ResetTrigger fun(name:string)
---@field ResetTrigger fun(id:number)
---@field IsParameterControlledByCurve fun(name:string):boolean
---@field IsParameterControlledByCurve fun(id:number):boolean
---@field GetIKPosition fun(goal:UnityEngine.AvatarIKGoal):UnityEngine.Vector3
---@field SetIKPosition fun(goal:UnityEngine.AvatarIKGoal, goalPosition:UnityEngine.Vector3)
---@field GetIKRotation fun(goal:UnityEngine.AvatarIKGoal):UnityEngine.Quaternion
---@field SetIKRotation fun(goal:UnityEngine.AvatarIKGoal, goalRotation:UnityEngine.Quaternion)
---@field GetIKPositionWeight fun(goal:UnityEngine.AvatarIKGoal):number
---@field SetIKPositionWeight fun(goal:UnityEngine.AvatarIKGoal, value:number)
---@field GetIKRotationWeight fun(goal:UnityEngine.AvatarIKGoal):number
---@field SetIKRotationWeight fun(goal:UnityEngine.AvatarIKGoal, value:number)
---@field GetIKHintPosition fun(hint:UnityEngine.AvatarIKHint):UnityEngine.Vector3
---@field SetIKHintPosition fun(hint:UnityEngine.AvatarIKHint, hintPosition:UnityEngine.Vector3)
---@field GetIKHintPositionWeight fun(hint:UnityEngine.AvatarIKHint):number
---@field SetIKHintPositionWeight fun(hint:UnityEngine.AvatarIKHint, value:number)
---@field SetLookAtPosition fun(lookAtPosition:UnityEngine.Vector3)
---@field SetLookAtWeight fun(weight:number)
---@field SetLookAtWeight fun(weight:number, bodyWeight:number)
---@field SetLookAtWeight fun(weight:number, bodyWeight:number, headWeight:number)
---@field SetLookAtWeight fun(weight:number, bodyWeight:number, headWeight:number, eyesWeight:number)
---@field SetLookAtWeight fun(weight:number, bodyWeight:number, headWeight:number, eyesWeight:number, clampWeight:number)
---@field SetBoneLocalRotation fun(humanBoneId:UnityEngine.HumanBodyBones, rotation:UnityEngine.Quaternion)
---@field GetBehaviour fun():nil
---@field GetBehaviours fun():T[]
---@field GetBehaviours fun(fullPathHash:number, layerIndex:number):UnityEngine.StateMachineBehaviour[]
---@field GetLayerName fun(layerIndex:number):string
---@field GetLayerIndex fun(layerName:string):number
---@field GetLayerWeight fun(layerIndex:number):number
---@field SetLayerWeight fun(layerIndex:number, weight:number)
---@field GetCurrentAnimatorStateInfo fun(layerIndex:number):UnityEngine.AnimatorStateInfo
---@field GetNextAnimatorStateInfo fun(layerIndex:number):UnityEngine.AnimatorStateInfo
---@field GetAnimatorTransitionInfo fun(layerIndex:number):UnityEngine.AnimatorTransitionInfo
---@field GetCurrentAnimatorClipInfoCount fun(layerIndex:number):number
---@field GetNextAnimatorClipInfoCount fun(layerIndex:number):number
---@field GetCurrentAnimatorClipInfo fun(layerIndex:number):UnityEngine.AnimatorClipInfo[]
---@field GetNextAnimatorClipInfo fun(layerIndex:number):UnityEngine.AnimatorClipInfo[]
---@field IsInTransition fun(layerIndex:number):boolean
---@field GetParameter fun(index:number):UnityEngine.AnimatorControllerParameter
---@field MatchTarget fun(matchPosition:UnityEngine.Vector3, matchRotation:UnityEngine.Quaternion, targetBodyPart:UnityEngine.AvatarTarget, weightMask:UnityEngine.MatchTargetWeightMask, startNormalizedTime:number)
---@field MatchTarget fun(matchPosition:UnityEngine.Vector3, matchRotation:UnityEngine.Quaternion, targetBodyPart:UnityEngine.AvatarTarget, weightMask:UnityEngine.MatchTargetWeightMask, startNormalizedTime:number, targetNormalizedTime:number)
---@field MatchTarget fun(matchPosition:UnityEngine.Vector3, matchRotation:UnityEngine.Quaternion, targetBodyPart:UnityEngine.AvatarTarget, weightMask:UnityEngine.MatchTargetWeightMask, startNormalizedTime:number, targetNormalizedTime:number, completeMatch:boolean)
---@field InterruptMatchTarget fun()
---@field InterruptMatchTarget fun(completeMatch:boolean)
---@field ForceStateNormalizedTime fun(normalizedTime:number)
---@field CrossFadeInFixedTime fun(stateName:string, fixedTransitionDuration:number)
---@field CrossFadeInFixedTime fun(stateName:string, fixedTransitionDuration:number, layer:number)
---@field CrossFadeInFixedTime fun(stateName:string, fixedTransitionDuration:number, layer:number, fixedTimeOffset:number)
---@field CrossFadeInFixedTime fun(stateName:string, fixedTransitionDuration:number, layer:number, fixedTimeOffset:number, normalizedTransitionTime:number)
---@field CrossFadeInFixedTime fun(stateHashName:number, fixedTransitionDuration:number, layer:number, fixedTimeOffset:number)
---@field CrossFadeInFixedTime fun(stateHashName:number, fixedTransitionDuration:number, layer:number)
---@field CrossFadeInFixedTime fun(stateHashName:number, fixedTransitionDuration:number)
---@field CrossFadeInFixedTime fun(stateHashName:number, fixedTransitionDuration:number, layer:number, fixedTimeOffset:number, normalizedTransitionTime:number)
---@field WriteDefaultValues fun()
---@field CrossFade fun(stateName:string, normalizedTransitionDuration:number, layer:number, normalizedTimeOffset:number)
---@field CrossFade fun(stateName:string, normalizedTransitionDuration:number, layer:number)
---@field CrossFade fun(stateName:string, normalizedTransitionDuration:number)
---@field CrossFade fun(stateName:string, normalizedTransitionDuration:number, layer:number, normalizedTimeOffset:number, normalizedTransitionTime:number)
---@field CrossFade fun(stateHashName:number, normalizedTransitionDuration:number, layer:number, normalizedTimeOffset:number, normalizedTransitionTime:number)
---@field CrossFade fun(stateHashName:number, normalizedTransitionDuration:number, layer:number, normalizedTimeOffset:number)
---@field CrossFade fun(stateHashName:number, normalizedTransitionDuration:number, layer:number)
---@field CrossFade fun(stateHashName:number, normalizedTransitionDuration:number)
---@field PlayInFixedTime fun(stateName:string, layer:number)
---@field PlayInFixedTime fun(stateName:string)
---@field PlayInFixedTime fun(stateName:string, layer:number, fixedTime:number)
---@field PlayInFixedTime fun(stateNameHash:number, layer:number, fixedTime:number)
---@field PlayInFixedTime fun(stateNameHash:number, layer:number)
---@field PlayInFixedTime fun(stateNameHash:number)
---@field Play fun(stateName:string, layer:number)
---@field Play fun(stateName:string)
---@field Play fun(stateName:string, layer:number, normalizedTime:number)
---@field Play fun(stateNameHash:number, layer:number, normalizedTime:number)
---@field Play fun(stateNameHash:number, layer:number)
---@field Play fun(stateNameHash:number)
---@field SetTarget fun(targetIndex:UnityEngine.AvatarTarget, targetNormalizedTime:number)
---@field IsControlled fun(transform:UnityEngine.Transform):boolean
---@field GetBoneTransform fun(humanBoneId:UnityEngine.HumanBodyBones):UnityEngine.Transform
---@field StartPlayback fun()
---@field StopPlayback fun()
---@field StartRecording fun(frameCount:number)
---@field StopRecording fun()
---@field HasState fun(layerIndex:number, stateID:number):boolean
---@field StringToHash fun(name:string):number
---@field Update fun(deltaTime:number)
---@field Rebind fun()
---@field ApplyBuiltinRootMotion fun()
---@field GetVector fun(name:string):UnityEngine.Vector3
---@field GetVector fun(id:number):UnityEngine.Vector3
---@field SetVector fun(name:string, value:UnityEngine.Vector3)
---@field SetVector fun(id:number, value:UnityEngine.Vector3)
---@field GetQuaternion fun(name:string):UnityEngine.Quaternion
---@field GetQuaternion fun(id:number):UnityEngine.Quaternion
---@field SetQuaternion fun(name:string, value:UnityEngine.Quaternion)
---@field SetQuaternion fun(id:number, value:UnityEngine.Quaternion)
---@field GetComponent fun(type:System.Type):UnityEngine.Component
---@field GetComponent fun():nil
---@field TryGetComponent fun(type:System.Type, component:UnityEngine.Component&):boolean
---@field TryGetComponent fun(component:nil):boolean
---@field GetComponent fun(type:string):UnityEngine.Component
---@field GetComponentInChildren fun(t:System.Type, includeInactive:boolean):UnityEngine.Component
---@field GetComponentInChildren fun(t:System.Type):UnityEngine.Component
---@field GetComponentInChildren fun(includeInactive:boolean):nil
---@field GetComponentInChildren fun():nil
---@field GetComponentsInChildren fun(t:System.Type, includeInactive:boolean):UnityEngine.Component[]
---@field GetComponentsInChildren fun(t:System.Type):UnityEngine.Component[]
---@field GetComponentsInChildren fun(includeInactive:boolean):T[]
---@field GetComponentsInChildren fun():T[]
---@field GetComponentInParent fun(t:System.Type):UnityEngine.Component
---@field GetComponentInParent fun():nil
---@field GetComponentsInParent fun(t:System.Type, includeInactive:boolean):UnityEngine.Component[]
---@field GetComponentsInParent fun(t:System.Type):UnityEngine.Component[]
---@field GetComponentsInParent fun(includeInactive:boolean):T[]
---@field GetComponentsInParent fun():T[]
---@field GetComponents fun(type:System.Type):UnityEngine.Component[]
---@field GetComponents fun():T[]
---@field CompareTag fun(tag:string):boolean
---@field SendMessageUpwards fun(methodName:string, value:System.Object, options:UnityEngine.SendMessageOptions)
---@field SendMessageUpwards fun(methodName:string, value:System.Object)
---@field SendMessageUpwards fun(methodName:string)
---@field SendMessageUpwards fun(methodName:string, options:UnityEngine.SendMessageOptions)
---@field SendMessage fun(methodName:string, value:System.Object)
---@field SendMessage fun(methodName:string)
---@field SendMessage fun(methodName:string, value:System.Object, options:UnityEngine.SendMessageOptions)
---@field SendMessage fun(methodName:string, options:UnityEngine.SendMessageOptions)
---@field BroadcastMessage fun(methodName:string, parameter:System.Object, options:UnityEngine.SendMessageOptions)
---@field BroadcastMessage fun(methodName:string, parameter:System.Object)
---@field BroadcastMessage fun(methodName:string)
---@field BroadcastMessage fun(methodName:string, options:UnityEngine.SendMessageOptions)
---@field GetInstanceID fun():number
---@field GetHashCode fun():number
---@field Equals fun(other:System.Object):boolean
---@field ToString fun():string
---@field GetType fun():System.Type
UnityEngine.Animator = {}
