---@class UnityEngine.TextAsset:UnityEngine.Object
---@field bytes System.Byte[]
---@field text string
---@field name string
---@field hideFlags UnityEngine.HideFlags
---@field ToString fun():string
---@field GetInstanceID fun():number
---@field GetHashCode fun():number
---@field Equals fun(other:System.Object):boolean
---@field GetType fun():System.Type
UnityEngine.TextAsset = {}
