---@class LuaInterface.InjectType:System.Enum
---@field Equals fun(obj:System.Object):boolean
---@field GetHashCode fun():number
---@field ToString fun():string
---@field ToString fun(format:string, provider:System.IFormatProvider):string
---@field CompareTo fun(target:System.Object):number
---@field ToString fun(format:string):string
---@field ToString fun(provider:System.IFormatProvider):string
---@field HasFlag fun(flag:System.Enum):boolean
---@field GetTypeCode fun():System.TypeCode
---@field GetType fun():System.Type
LuaInterface.InjectType = {}
