---@class UnityEngine.RectTransform:UnityEngine.Transform
---@field rect UnityEngine.Rect
---@field anchorMin UnityEngine.Vector2
---@field anchorMax UnityEngine.Vector2
---@field anchoredPosition UnityEngine.Vector2
---@field sizeDelta UnityEngine.Vector2
---@field pivot UnityEngine.Vector2
---@field anchoredPosition3D UnityEngine.Vector3
---@field offsetMin UnityEngine.Vector2
---@field offsetMax UnityEngine.Vector2
---@field position UnityEngine.Vector3
---@field localPosition UnityEngine.Vector3
---@field eulerAngles UnityEngine.Vector3
---@field localEulerAngles UnityEngine.Vector3
---@field right UnityEngine.Vector3
---@field up UnityEngine.Vector3
---@field forward UnityEngine.Vector3
---@field rotation UnityEngine.Quaternion
---@field localRotation UnityEngine.Quaternion
---@field localScale UnityEngine.Vector3
---@field parent UnityEngine.Transform
---@field worldToLocalMatrix UnityEngine.Matrix4x4
---@field localToWorldMatrix UnityEngine.Matrix4x4
---@field root UnityEngine.Transform
---@field childCount number
---@field lossyScale UnityEngine.Vector3
---@field hasChanged boolean
---@field hierarchyCapacity number
---@field hierarchyCount number
---@field transform UnityEngine.Transform
---@field gameObject UnityEngine.GameObject
---@field tag string
---@field rigidbody UnityEngine.Component
---@field rigidbody2D UnityEngine.Component
---@field camera UnityEngine.Component
---@field light UnityEngine.Component
---@field animation UnityEngine.Component
---@field constantForce UnityEngine.Component
---@field renderer UnityEngine.Component
---@field audio UnityEngine.Component
---@field networkView UnityEngine.Component
---@field collider UnityEngine.Component
---@field collider2D UnityEngine.Component
---@field hingeJoint UnityEngine.Component
---@field particleSystem UnityEngine.Component
---@field name string
---@field hideFlags UnityEngine.HideFlags
---@field ForceUpdateRectTransforms fun()
---@field GetLocalCorners fun(fourCornersArray:UnityEngine.Vector3[])
---@field GetWorldCorners fun(fourCornersArray:UnityEngine.Vector3[])
---@field SetInsetAndSizeFromParentEdge fun(edge:UnityEngine.RectTransform.Edge, inset:number, size:number)
---@field SetSizeWithCurrentAnchors fun(axis:UnityEngine.RectTransform.Axis, size:number)
---@field SetParent fun(p:UnityEngine.Transform)
---@field SetParent fun(parent:UnityEngine.Transform, worldPositionStays:boolean)
---@field SetPositionAndRotation fun(position:UnityEngine.Vector3, rotation:UnityEngine.Quaternion)
---@field Translate fun(translation:UnityEngine.Vector3, relativeTo:UnityEngine.Space)
---@field Translate fun(translation:UnityEngine.Vector3)
---@field Translate fun(x:number, y:number, z:number, relativeTo:UnityEngine.Space)
---@field Translate fun(x:number, y:number, z:number)
---@field Translate fun(translation:UnityEngine.Vector3, relativeTo:UnityEngine.Transform)
---@field Translate fun(x:number, y:number, z:number, relativeTo:UnityEngine.Transform)
---@field Rotate fun(eulers:UnityEngine.Vector3, relativeTo:UnityEngine.Space)
---@field Rotate fun(eulers:UnityEngine.Vector3)
---@field Rotate fun(xAngle:number, yAngle:number, zAngle:number, relativeTo:UnityEngine.Space)
---@field Rotate fun(xAngle:number, yAngle:number, zAngle:number)
---@field Rotate fun(axis:UnityEngine.Vector3, angle:number, relativeTo:UnityEngine.Space)
---@field Rotate fun(axis:UnityEngine.Vector3, angle:number)
---@field RotateAround fun(point:UnityEngine.Vector3, axis:UnityEngine.Vector3, angle:number)
---@field LookAt fun(target:UnityEngine.Transform, worldUp:UnityEngine.Vector3)
---@field LookAt fun(target:UnityEngine.Transform)
---@field LookAt fun(worldPosition:UnityEngine.Vector3, worldUp:UnityEngine.Vector3)
---@field LookAt fun(worldPosition:UnityEngine.Vector3)
---@field TransformDirection fun(direction:UnityEngine.Vector3):UnityEngine.Vector3
---@field TransformDirection fun(x:number, y:number, z:number):UnityEngine.Vector3
---@field InverseTransformDirection fun(direction:UnityEngine.Vector3):UnityEngine.Vector3
---@field InverseTransformDirection fun(x:number, y:number, z:number):UnityEngine.Vector3
---@field TransformVector fun(vector:UnityEngine.Vector3):UnityEngine.Vector3
---@field TransformVector fun(x:number, y:number, z:number):UnityEngine.Vector3
---@field InverseTransformVector fun(vector:UnityEngine.Vector3):UnityEngine.Vector3
---@field InverseTransformVector fun(x:number, y:number, z:number):UnityEngine.Vector3
---@field TransformPoint fun(position:UnityEngine.Vector3):UnityEngine.Vector3
---@field TransformPoint fun(x:number, y:number, z:number):UnityEngine.Vector3
---@field InverseTransformPoint fun(position:UnityEngine.Vector3):UnityEngine.Vector3
---@field InverseTransformPoint fun(x:number, y:number, z:number):UnityEngine.Vector3
---@field DetachChildren fun()
---@field SetAsFirstSibling fun()
---@field SetAsLastSibling fun()
---@field SetSiblingIndex fun(index:number)
---@field GetSiblingIndex fun():number
---@field Find fun(n:string):UnityEngine.Transform
---@field IsChildOf fun(parent:UnityEngine.Transform):boolean
---@field FindChild fun(n:string):UnityEngine.Transform
---@field RotateAround fun(axis:UnityEngine.Vector3, angle:number)
---@field RotateAroundLocal fun(axis:UnityEngine.Vector3, angle:number)
---@field GetChild fun(index:number):UnityEngine.Transform
---@field GetChildCount fun():number
---@field GetComponent fun(type:System.Type):UnityEngine.Component
---@field GetComponent fun():nil
---@field TryGetComponent fun(type:System.Type, component:UnityEngine.Component&):boolean
---@field TryGetComponent fun(component:nil):boolean
---@field GetComponent fun(type:string):UnityEngine.Component
---@field GetComponentInChildren fun(t:System.Type, includeInactive:boolean):UnityEngine.Component
---@field GetComponentInChildren fun(t:System.Type):UnityEngine.Component
---@field GetComponentInChildren fun(includeInactive:boolean):nil
---@field GetComponentInChildren fun():nil
---@field GetComponentsInChildren fun(t:System.Type, includeInactive:boolean):UnityEngine.Component[]
---@field GetComponentsInChildren fun(t:System.Type):UnityEngine.Component[]
---@field GetComponentsInChildren fun(includeInactive:boolean):T[]
---@field GetComponentsInChildren fun():T[]
---@field GetComponentInParent fun(t:System.Type):UnityEngine.Component
---@field GetComponentInParent fun():nil
---@field GetComponentsInParent fun(t:System.Type, includeInactive:boolean):UnityEngine.Component[]
---@field GetComponentsInParent fun(t:System.Type):UnityEngine.Component[]
---@field GetComponentsInParent fun(includeInactive:boolean):T[]
---@field GetComponentsInParent fun():T[]
---@field GetComponents fun(type:System.Type):UnityEngine.Component[]
---@field GetComponents fun():T[]
---@field CompareTag fun(tag:string):boolean
---@field SendMessageUpwards fun(methodName:string, value:System.Object, options:UnityEngine.SendMessageOptions)
---@field SendMessageUpwards fun(methodName:string, value:System.Object)
---@field SendMessageUpwards fun(methodName:string)
---@field SendMessageUpwards fun(methodName:string, options:UnityEngine.SendMessageOptions)
---@field SendMessage fun(methodName:string, value:System.Object)
---@field SendMessage fun(methodName:string)
---@field SendMessage fun(methodName:string, value:System.Object, options:UnityEngine.SendMessageOptions)
---@field SendMessage fun(methodName:string, options:UnityEngine.SendMessageOptions)
---@field BroadcastMessage fun(methodName:string, parameter:System.Object, options:UnityEngine.SendMessageOptions)
---@field BroadcastMessage fun(methodName:string, parameter:System.Object)
---@field BroadcastMessage fun(methodName:string)
---@field BroadcastMessage fun(methodName:string, options:UnityEngine.SendMessageOptions)
---@field GetInstanceID fun():number
---@field GetHashCode fun():number
---@field Equals fun(other:System.Object):boolean
---@field ToString fun():string
---@field GetType fun():System.Type
UnityEngine.RectTransform = {}
