//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AssetTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(AssetType));
		L.RegVar("UnityObject", get_UnityObject, null);
		L.RegVar("GameObject", get_GameObject, null);
		L.RegVar("Material", get_Material, null);
		L.RegVar("Sprite", get_Sprite, null);
		L.RegVar("Texture", get_Texture, null);
		L.RegVar("AnimationClip", get_AnimationClip, null);
		L.RegVar("VideoClip", get_VideoClip, null);
		L.RegVar("Scene", get_Scene, null);
		L.RegVar("TextAsset", get_TextAsset, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<AssetType>.Check = CheckType;
		StackTraits<AssetType>.Push = Push;
	}

	static void Push(IntPtr L, AssetType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(AssetType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UnityObject(IntPtr L)
	{
		ToLua.Push(L, AssetType.UnityObject);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GameObject(IntPtr L)
	{
		ToLua.Push(L, AssetType.GameObject);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Material(IntPtr L)
	{
		ToLua.Push(L, AssetType.Material);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Sprite(IntPtr L)
	{
		ToLua.Push(L, AssetType.Sprite);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Texture(IntPtr L)
	{
		ToLua.Push(L, AssetType.Texture);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AnimationClip(IntPtr L)
	{
		ToLua.Push(L, AssetType.AnimationClip);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_VideoClip(IntPtr L)
	{
		ToLua.Push(L, AssetType.VideoClip);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Scene(IntPtr L)
	{
		ToLua.Push(L, AssetType.Scene);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TextAsset(IntPtr L)
	{
		ToLua.Push(L, AssetType.TextAsset);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		AssetType o = (AssetType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

