//this source code was auto-generated by tolua#, do not modify it
using System;
using DG.Tweening;
using LuaInterface;

public class UnityEngine_UIElements_ScrollViewWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.UIElements.ScrollView), typeof(UnityEngine.UIElements.VisualElement));
		L.RegFunction("ScrollTo", ScrollTo);
		L.RegFunction("New", _CreateUnityEngine_UIElements_ScrollView);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("ussClassName", get_ussClassName, null);
		L.RegVar("viewportUssClassName", get_viewportUssClassName, null);
		L.RegVar("contentAndVerticalScrollUssClassName", get_contentAndVerticalScrollUssClassName, null);
		L.RegVar("contentUssClassName", get_contentUssClassName, null);
		L.RegVar("hScrollerUssClassName", get_hScrollerUssClassName, null);
		L.RegVar("vScrollerUssClassName", get_vScrollerUssClassName, null);
		L.RegVar("horizontalVariantUssClassName", get_horizontalVariantUssClassName, null);
		L.RegVar("verticalVariantUssClassName", get_verticalVariantUssClassName, null);
		L.RegVar("verticalHorizontalVariantUssClassName", get_verticalHorizontalVariantUssClassName, null);
		L.RegVar("scrollVariantUssClassName", get_scrollVariantUssClassName, null);
		L.RegVar("horizontalScrollerVisibility", get_horizontalScrollerVisibility, set_horizontalScrollerVisibility);
		L.RegVar("verticalScrollerVisibility", get_verticalScrollerVisibility, set_verticalScrollerVisibility);
		L.RegVar("scrollOffset", get_scrollOffset, set_scrollOffset);
		L.RegVar("horizontalPageSize", get_horizontalPageSize, set_horizontalPageSize);
		L.RegVar("verticalPageSize", get_verticalPageSize, set_verticalPageSize);
		L.RegVar("scrollDecelerationRate", get_scrollDecelerationRate, set_scrollDecelerationRate);
		L.RegVar("elasticity", get_elasticity, set_elasticity);
		L.RegVar("touchScrollBehavior", get_touchScrollBehavior, set_touchScrollBehavior);
		L.RegVar("contentViewport", get_contentViewport, null);
		L.RegVar("horizontalScroller", get_horizontalScroller, null);
		L.RegVar("verticalScroller", get_verticalScroller, null);
		L.RegVar("contentContainer", get_contentContainer, null);
		L.RegVar("mode", get_mode, set_mode);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_UIElements_ScrollView(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UnityEngine.UIElements.ScrollView obj = new UnityEngine.UIElements.ScrollView();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1)
			{
				UnityEngine.UIElements.ScrollViewMode arg0 = (UnityEngine.UIElements.ScrollViewMode)ToLua.CheckObject(L, 1, typeof(UnityEngine.UIElements.ScrollViewMode));
				UnityEngine.UIElements.ScrollView obj = new UnityEngine.UIElements.ScrollView(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.UIElements.ScrollView.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ScrollTo(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)ToLua.CheckObject<UnityEngine.UIElements.ScrollView>(L, 1);
			UnityEngine.UIElements.VisualElement arg0 = (UnityEngine.UIElements.VisualElement)ToLua.CheckObject<UnityEngine.UIElements.VisualElement>(L, 2);
			obj.ScrollTo(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ussClassName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, UnityEngine.UIElements.ScrollView.ussClassName);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_viewportUssClassName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, UnityEngine.UIElements.ScrollView.viewportUssClassName);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_contentAndVerticalScrollUssClassName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, UnityEngine.UIElements.ScrollView.contentAndVerticalScrollUssClassName);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_contentUssClassName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, UnityEngine.UIElements.ScrollView.contentUssClassName);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_hScrollerUssClassName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, UnityEngine.UIElements.ScrollView.hScrollerUssClassName);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_vScrollerUssClassName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, UnityEngine.UIElements.ScrollView.vScrollerUssClassName);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_horizontalVariantUssClassName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, UnityEngine.UIElements.ScrollView.horizontalVariantUssClassName);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_verticalVariantUssClassName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, UnityEngine.UIElements.ScrollView.verticalVariantUssClassName);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_verticalHorizontalVariantUssClassName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, UnityEngine.UIElements.ScrollView.verticalHorizontalVariantUssClassName);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_scrollVariantUssClassName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, UnityEngine.UIElements.ScrollView.scrollVariantUssClassName);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_horizontalScrollerVisibility(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			UnityEngine.UIElements.ScrollerVisibility ret = obj.horizontalScrollerVisibility;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index horizontalScrollerVisibility on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_verticalScrollerVisibility(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			UnityEngine.UIElements.ScrollerVisibility ret = obj.verticalScrollerVisibility;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index verticalScrollerVisibility on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_scrollOffset(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			UnityEngine.Vector2 ret = obj.scrollOffset;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index scrollOffset on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_horizontalPageSize(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			float ret = obj.horizontalPageSize;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index horizontalPageSize on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_verticalPageSize(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			float ret = obj.verticalPageSize;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index verticalPageSize on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_scrollDecelerationRate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			float ret = obj.scrollDecelerationRate;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index scrollDecelerationRate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_elasticity(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			float ret = obj.elasticity;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index elasticity on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_touchScrollBehavior(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			UnityEngine.UIElements.ScrollView.TouchScrollBehavior ret = obj.touchScrollBehavior;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index touchScrollBehavior on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_contentViewport(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			UnityEngine.UIElements.VisualElement ret = obj.contentViewport;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index contentViewport on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_horizontalScroller(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			UnityEngine.UIElements.Scroller ret = obj.horizontalScroller;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index horizontalScroller on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_verticalScroller(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			UnityEngine.UIElements.Scroller ret = obj.verticalScroller;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index verticalScroller on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_contentContainer(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			UnityEngine.UIElements.VisualElement ret = obj.contentContainer;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index contentContainer on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			UnityEngine.UIElements.ScrollViewMode ret = obj.mode;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mode on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_horizontalScrollerVisibility(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			UnityEngine.UIElements.ScrollerVisibility arg0 = (UnityEngine.UIElements.ScrollerVisibility)ToLua.CheckObject(L, 2, typeof(UnityEngine.UIElements.ScrollerVisibility));
			obj.horizontalScrollerVisibility = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index horizontalScrollerVisibility on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_verticalScrollerVisibility(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			UnityEngine.UIElements.ScrollerVisibility arg0 = (UnityEngine.UIElements.ScrollerVisibility)ToLua.CheckObject(L, 2, typeof(UnityEngine.UIElements.ScrollerVisibility));
			obj.verticalScrollerVisibility = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index verticalScrollerVisibility on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_scrollOffset(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			UnityEngine.Vector2 arg0 = ToLua.ToVector2(L, 2);
			obj.scrollOffset = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index scrollOffset on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_horizontalPageSize(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.horizontalPageSize = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index horizontalPageSize on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_verticalPageSize(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.verticalPageSize = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index verticalPageSize on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_scrollDecelerationRate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.scrollDecelerationRate = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index scrollDecelerationRate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_elasticity(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.elasticity = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index elasticity on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_touchScrollBehavior(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			UnityEngine.UIElements.ScrollView.TouchScrollBehavior arg0 = (UnityEngine.UIElements.ScrollView.TouchScrollBehavior)ToLua.CheckObject(L, 2, typeof(UnityEngine.UIElements.ScrollView.TouchScrollBehavior));
			obj.touchScrollBehavior = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index touchScrollBehavior on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mode(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UIElements.ScrollView obj = (UnityEngine.UIElements.ScrollView)o;
			UnityEngine.UIElements.ScrollViewMode arg0 = (UnityEngine.UIElements.ScrollViewMode)ToLua.CheckObject(L, 2, typeof(UnityEngine.UIElements.ScrollViewMode));
			obj.mode = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mode on a nil value");
		}
	}
}

